---
- name: Update and restart containerd
  hosts: node_exporters
  become: yes

  tasks:
    - name: Copy config.toml to remote machines
      copy:
        src: ../templates/config.toml
        dest: /etc/containerd/config.toml
        owner: root
        group: root
        mode: '0644'

    - name: Restart containerd service
      systemd:
        name: containerd
        state: restarted