---
- hosts: master
  become: yes
  vars_files:
    - ../vars/vars_manual.yml
  tasks:
    - name: Download the latest version of Helm binary
      get_url:
        url: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
        dest: /tmp/helm.tar.gz
        mode: '0755'
    
    - name: Extract Helm archive
      unarchive:
        src: /tmp/helm.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        extra_opts:
          - --strip-components=1
    
    - name: Remove temporary file
      file:
        path: /tmp/helm.tar.gz
        state: absent
    
    - name: Check if Helm is installed correctly
      command: helm version
      register: helm_output
    
    - debug:
        var: helm_output.stdout_lines
