---
- name: Setup Prometheus
  hosts: srvserv
  become: yes

  tasks:
    - name: Install required dependencies
      apt:
        name: 
          - wget
          - tar
        state: present
        update_cache: yes

    - name: Download Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.46.0/prometheus-2.46.0.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Move Prometheus binaries
      command: mv /tmp/prometheus-2.46.0.linux-amd64/{{ item }} /usr/local/bin/
      with_items:
        - prometheus
        - promtool
    
    - name: Create Prometheus user and group
      user:
        name: prometheus
        shell: /usr/sbin/nologin
        system: yes
        create_home: no

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Move Prometheus config and other files
      copy:
        src: /tmp/prometheus-2.46.0.linux-amd64/{{ item }}
        dest: /etc/prometheus/
        remote_src: yes
      with_items:
        - consoles
        - console_libraries

    - name: Copy Prometheus configuration from local file
      copy:
        src: ../templates/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'
        
    - name: Ensure the directory for alert rules exists
      file:
        path: /etc/prometheus/rules
        state: directory
        mode: '0755'

    - name: Copy local alert_rules.yml to the remote server
      template:
        src: ../templates/alert_rules.yml  # Local path to your alert_rules.yml file
        dest: /etc/prometheus/rules/alert_rules.yml
        mode: '0644'

    - name: Setup Prometheus systemd service
      copy:
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus \
            --web.console.templates=/etc/prometheus/consoles \
            --web.console.libraries=/etc/prometheus/console_libraries

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/prometheus.service
        mode: '0644'

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes
    
    - name: Restart Prometheus to apply the new alert rules
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
        
- name: Install Node Exporter
  hosts: all
  become: yes

  tasks:
    - name: Install required dependencies
      apt:
        name: 
          - wget
          - tar
        state: present
        update_cache: yes

    - name: Download Node Exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Move Node Exporter binary
      command: mv /tmp/node_exporter-1.6.0.linux-amd64/node_exporter /usr/local/bin/

    - name: Create node_exporter user
      user:
        name: node_exporter
        shell: /usr/sbin/nologin
        system: yes
        create_home: no
    
    - name: Create Node Exporter systemd service
      copy:
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/node_exporter.service
        mode: '0644'

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Start and enable Node Exporter service
      systemd:
        name: node_exporter
        state: started
        enabled: yes
